services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: kludb
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"

  backend:
    container_name: springboot
    build:
      context: ./STUDENTAPI-SPRINGBOOT
      dockerfile: ../STUDENTAPI-FULLSTACK/backend.Dockerfile
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./STUDENTAPI-REACT
      dockerfile: ../STUDENTAPI-FULLSTACK/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
